### ISSUE TITLE
Enable arbitrary naming of BaseOccurrence subclasses

### ISSUE THREAD

**Issue by gregplaysguitar** [gregplaysguitar/django-eventtools#12]
Currently only works if the class is called Occurrence; could mandate a related_name but that'll break backwards compatibility

**Comment by kmahelona** [comment]
Is this related to this error I'm getting:

> AttributeError: 'MyEvent' object has no attribute 'occurrence_set'

FYI my models are:

`
class MyEvent(BaseEvent)
`
`class MyEventOccurrence(BaseOccurrence)`

**Comment by gregplaysguitar** [comment]
Yeah it is, sorry. Currently the class has to be called Occurrence

**Comment by gregplaysguitar** [comment]
Ok, this is now fixed in 0.9.11
