### ISSUE TITLE
Biweekly

### ISSUE THREAD

**Issue by sophianachiba** [gregplaysguitar/django-eventtools#15]
Hello,

I'm looking to see if there's a way to add a biweekly, that's once every 2 weeks.
I'm happy to update your code also but I would need some guidance.

Thanks.

**Comment by gregplaysguitar** [comment]
Hi,

You can achieve this by adding custom rrulestr definitions in your settings. See `REPEAT_CHOICES` at the top of `eventtools/models.py`

In your case you'll probably just want the following in your django settings file:

    EVENTTOOLS_REPEAT_CHOICES = (
        ("RRULE:FREQ=DAILY", 'Daily'),
        ("RRULE:FREQ=WEEKLY", 'Weekly'),
        ("RRULE:FREQ=WEEKLY;INTERVAL=2", 'Bi-weekly'),
        ("RRULE:FREQ=MONTHLY", 'Monthly'),
        ("RRULE:FREQ=YEARLY", 'Yearly'),
    )

**Comment by gregplaysguitar** [comment]
Have added this to the readme:

https://github.com/gregplaysguitar/django-eventtools/blob/master/README.md#custom-repeat-intervals
