### ISSUE TITLE
Does not handle timezone transitions on event recurrence

### ISSUE THREAD

**Issue by isolationism** [gregplaysguitar/django-eventtools#17]
If you create an event that starts during daylight or standard time that recurs, and as a result of that recurrence, crosses the boundary to the other time, the event times on the other side of the boundary will be skewed.

Example:

On an EST5EDT system, the offset from UTC is currently -0500hrs. If you create an event that first occurs on November 5 that starts at 10AM, and recurs once a week, it will show as starting at 9AM on the second occurrence. 

I think the problem may be related to when the timezone conversion is applied; I think a naïve datetime has to be sent to the repeater then localized after iteration.

**Comment by gregplaysguitar** [comment]
Good catch, thanks. I'll have a look at this as soon as I get a chance.

**Comment by gregplaysguitar** [comment]
Thanks for the PR - this issue should be fixed now in master. I've added tests, but could you check it solves the problem in your application, and check that my tests are correctly demonstrating the issue you had? Thanks!

**Comment by isolationism** [comment]
Greg, everything is looking good here—The unit test covers my test case and the software behaves as it should in my application. Grateful for the upstream fix, hope to see it in a new release soon! I'll close my PR now. Cheers.

**Comment by gregplaysguitar** [comment]
Great to hear. Have released v0.9.9
