### ISSUE TITLE
Django Admin?

### ISSUE THREAD

**Issue by JMurph2015** [gregplaysguitar/django-eventtools#19]
I can't seem to register these like other models in django admin.

**Comment by gregplaysguitar** [comment]
The models are abstract, you need to inherit from them in order to use them

https://github.com/gregplaysguitar/django-eventtools/blob/master/README.md#setup

**Comment by JMurph2015** [comment]
That's the problem.  Even when I inherit from them and try to register the child models, they don't show up whatsoever in the admin.  I did it pretty much identically to the example in the README (admittedly with some additional fields)

**Comment by gregplaysguitar** [comment]
Ok, it works fine for me - can you provide a reproducible test case?

**Comment by JMurph2015** [comment]
Edit, on a new database instance, it worked.  I didn't precisely replicate my steps though because the first time I migrated on an existing database.  However for me I think the case is closed.
