### ISSUE TITLE
pagination?

### ISSUE THREAD

**Issue by fb-erik** [gregplaysguitar/django-eventtools#23]
Since all_occurrences doesn't return a queryset but a generator object, how would you go about paginating all occurrences?

**Comment by gregplaysguitar** [comment]
Good question - if you knew it was a finite and manageable number, you could convert it to a list:

    occurrences = list(obj.all_occurrences())

Otherwise you could group them by date via the from_date and to_date arguments.

Does that help?

**Comment by fb-erik** [comment]
Interesting, I'm using recurring events so I ended up using from and to dates with a context variable called next which is just to_date + 1, but I still want to be able to show the upcoming x number of events in other places so turning it into a list sounds like a good idea. Thanks.
