### ISSUE TITLE
Returning N occurrences between a start and end date.

### ISSUE THREAD

**Issue by decko** [gregplaysguitar/django-eventtools#24]
Shouldn't all_occurrences method return all the occurrences between a start and end date?

Ex: If I set repeat with a rrulestr like "RRULE:FREQ=DAILY:BYDAY=FR,MO", shouldn't it return all Fridays and Mondays occurrences between the start and end dates?

**Comment by gregplaysguitar** [comment]
This is how it should work, but there's an arbitrary limit of 200 occurrences for sanity - is that what you're hitting?

**Comment by gregplaysguitar** [comment]
You can override that with the limit argument to all_occurrences

**Comment by decko** [comment]
https://gitlab.com/decko/epracas-backend/blob/atividades-api/atividades/tests/test_agenda.py#L145-164

**Comment by decko** [comment]
This is the test that I'm using: https://gitlab.com/decko/epracas-backend/blob/atividades-api/atividades/tests/test_agenda.py#L145-164

When I try to use list(obj.all_ocurrences()) it returns something like this:

> [(datetime.datetime(2017, 2, 2, 0, 0), datetime.datetime(2017, 2, 15, 0, 0), <Ocorrencia: 2017-02-01 00:00:00>), (datetime.datetime(2017, 2, 7, 0, 0), datetime.datetime(2017, 2, 20, 0, 0), <Ocorrencia: 2017-02-01 00:00:00>), (datetime.datetime(2017, 2, 9, 0, 0), datetime.datetime(2017, 2, 22, 0, 0), <Ocorrencia: 2017-02-01 00:00:00>), (datetime.datetime(2017, 2, 14, 0, 0), datetime.datetime(2017, 2, 27, 0, 0), <Ocorrencia: 2017-02-01 00:00:00>)]

**Comment by gregplaysguitar** [comment]
Ah ok, you need to use the `repeat_until` parameter instead of `end`. `end` is the end time of the individual occurrence. Also, your end is before your start in that example.

**Comment by decko** [comment]
Thanks man! Got it here.
