### ISSUE TITLE
TypeError returned when event.next_occurrence() doesn't exist.

### ISSUE THREAD

**Issue by kmahelona** [gregplaysguitar/django-eventtools#25]
tldr; should `event.next_occurrence()` return `None` rather than failing?

Maybe I'm not using django-eventtools properly, but the nice thing about next_occurrence() is I don't have to worry about any other occurrence in the event; however, if there are no future occurrences, then event.next_occurrence throws a `TypeError` with `'NoneType' object is not iterable`.

Handling the `TypeError` seems a bit too generic, so would a custom `OccurrenceError` or simply returning `None`  be more useful here?

Cheers!

**Comment by gregplaysguitar** [comment]
Sounds completely sensible to me. Feel free to make a PR, otherwise I'll get to this as soon as I have time.

**Comment by gregplaysguitar** [comment]
Just having a look at this, I couldn't reproduce the TypeError - have you got a code snippet that reproduces the problem?

**Comment by andrewfam** [comment]
Having the same issue too.

for reminder in active_reminders:
        email.send_reminder(reminder)
        if reminder.repeat == 'FREQ=DAILY;INTERVAL=1;COUNT=1':
            #ONLY ONE
            reminder.next = None
        else:
            reminder.next = reminder.next_occurrence(from_date=timezone.now())[0]
        reminder.save()

**Comment by kmahelona** [comment]
I'm doing this,

`event.next_occurrence(from_date=timezone.now())`

so maybe it's because my from date is in the future and the last event occurrence was in the past?

**Comment by kmahelona** [comment]
Ah ok, so if I just do,

`instance = event.next_occurrence(from_date=timezone.now())`

I'll get `None`; however doing 

`(start, end, instance) = event.next_occurrence(from_date=timezone.now())`

raises the `'NoneType' object is not iterable` error which makes sense because the code is probably trying to iterate the `None` instance so it can give me start and end.

I think an improvement would be to return `(None, None, None)` instead?

**Comment by gregplaysguitar** [comment]
Ah... yes that makes more sense. I don't think it should return `(None, None, None)` because then you wouldn't be able to do 

    if event.next_occurrence(from_date=timezone.now()):
        ...

It could generate a custom exception as you suggested above, but that might be getting a bit complex? I think returning `None` is probably best.

**Comment by kmahelona** [comment]
Got it. I'm not used to the returning of tuples ;).
