### ISSUE TITLE
Clarifications for next_occurrence and all_occurrences

### ISSUE THREAD

**Issue by andrewfam** [gregplaysguitar/django-eventtools#28]
I've got a base occurrence with the following 
next --> datetime.datetime(2017, 12, 24, 16, 0, tzinfo=<UTC>) or 2017-12-24 10:00:00-06 (SGT)
repeat --> u'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR;INTERVAL=1'

calling next_occurrence(from_date=timezone.now()) whereby timezone.now() is datetime.datetime(2017, 12, 26, 15, 49, 58, 221887, tzinfo=<UTC>) seems to be pulling dates from before the above see below which is calling for a date on the 25th instead of the 27th.

(datetime.datetime(2017, 12, 25, 0, 0, tzinfo=<DstTzInfo 'Asia/Singapore' SGT+8:00:00 STD>), datetime.datetime(2017, 12, 28, 1, 0, tzinfo=<DstTzInfo 'Asia/Singapore' SGT+8:00:00 STD>), <TaskRem: 2017-05-30 16:00:00+00:00>)

I have to do the following to get the next date:

nlist = self.all_occurrences(from_date=timezone.now())
next = None

for x in nlist:
                    if x[0] > timezone.now():
                        next = x[0]
                        break

Some clarifications on next_occurence would be good

**Comment by gregplaysguitar** [comment]
Hi, I couldn't reproduce this, but if you could provide a reduced test case which demonstrates the problem I'll have another look? I added a test using the SG timezone which is passing, feel free to use that as a starting point. See https://github.com/gregplaysguitar/django-eventtools/blob/master/tests/tests.py#L458
