### ISSUE TITLE
repeat_until as datetimefield instead of datefield

### ISSUE THREAD

**Issue by museroom** [gregplaysguitar/django-eventtools#29]
datetimefield is neccessary for occurrences that change in the middle of day. Is that possible?

**Comment by gregplaysguitar** [comment]
Hi, I could swap out the date for a datetime, but I've never had a use for that - what do you mean by "change in the middle of day"?

**Comment by museroom** [comment]
[example schedule(link):](https://storage.googleapis.com/museroom/pulse-media-mjpg/datetime.png)
Expected behaviour, play daily, stop at 2018-02-11 6pm. 
Actual behaviour (uncertain without datetime), play daily, stop at 2018-02-11 23:59pm. ?

**Comment by museroom** [comment]
ok I understand after reading the source,
as_datetime(self.repeat_until, True) < to_date
it check against "to_date", thx, no trouble. case close.
