### ISSUE TITLE
[enhancement]Use rrulestr for repeat

### ISSUE THREAD

**Issue by pgcd** [gregplaysguitar/django-eventtools#3]
I realize this may be outside the scope of this library, but I found myself in need of using a wider array of options from rrule, since I need to be able to integrate Google Calendar JSON output.
On the face of it, the easiest way out would be to use a string for BaseOccurrence.repeat, instead of an integer, and update the code to get the repeater accordingly. If I'm not mistaken, the change should have a relatively minor performance hit because it looks like the repeater and the generators do most of the work. This would also have the added benefit of allowing rrulesets without (I think) any other code changes.
Alternatively, to ensure backwards compatibility, a new BaseOccurrence.repeat_str field could be added, with checks to ensure only one of the rules is used and a conditional to decide which field should be used to create the repeater.
Given the scope of this, I'll wait for your feedback before proceeding.

**Comment by gregplaysguitar** [comment]
Actually, I always thought something like this might be useful - I've just never had the need for more complicated repetition. The main thing for me is that it doesn't complicate the admin interface for my existing users (none of whom are going to be writing their own rrules).

I think my preferred option would be to make the repeat value a string, and then make the choices configurable via django settings. That way you can either add the values you need (if you know them in advance) or set the value to `None` to make it a free text field. 

The downside of course is that it'll break backwards compatibility, but I think that's ok given the pre-1.0 status of the library, and small number of users.

Would that solve your problem?

**Comment by pgcd** [comment]
That should work for me - my use case doesn't really involve manual editing
of the rrule in any case. I will try and have a PR ready in the next couple
of days.
