### ISSUE TITLE
Export events as iCalendar?

### ISSUE THREAD

**Issue by whatrocks** [gregplaysguitar/django-eventtools#30]
Is it possible to export events in the iCalendar format?

**Comment by gregplaysguitar** [comment]
It is, but I think that's out of scope of this lib. Looks like django-ical might do what you want? https://django-ics.readthedocs.io/en/latest/

**Comment by whatrocks** [comment]
Thanks will check that out, too. I'm working with the Django Rest Framework and looking to create very simple one-time or recurring events, and your library looks great for this purpose. But down the road, I could see needed to export these events as some format (iCalendar?) that could imported into Google Cal etc.

**Comment by gregplaysguitar** [comment]
Cool, good luck!
