### ISSUE TITLE
i18n for BaseOccurrence model

### ISSUE THREAD

**Issue by jackill88** [gregplaysguitar/django-eventtools#34]
add verbose_name to BaseOccurrence's model fields to help spread this library across non-english countries

    start = models.DateTimeField(db_index=True [, verbose_name='start'])
    end = models.DateTimeField(db_index=True, null=True, blank=True [, verbose_name='end'])

    repeat = ChoiceTextField(choices=REPEAT_CHOICES, default='', blank=True [, verbose_name='repeat'])
    repeat_until = models.DateField(null=True, blank=True [, verbose_name='repeat_until'])

**Comment by gregplaysguitar** [comment]
See #36
