### ISSUE TITLE
Publish wheel

### ISSUE THREAD

**Issue by vsalvino** [gregplaysguitar/django-eventtools#39]
I'm wondering if there is any reason why wheels (`.whl`) are not being published in addition to the source distributions? One advantage to wheels from the python infrastructure standpoint is they install much faster as PyPI is able to pre-resolve the dependencies. And if your package is "pure" python (no C extensions) then building a wheel is very simple.

I am trying to optimize our dependency tree (coderedcms) and am therefore reaching out to any of our dependencies who do not yet publish in wheel format. Let me know if you are able to do this - I would be happy to help.

The command to build both source distribution and wheel is:

```
python setup.py sdist bdist_wheel
```

Then upload both as usual to PyPI.

**Comment by gregplaysguitar** [comment]
Great suggestion, thanks. I've published v1.0.3 with wheel included - let me know if that's working as expected

**Comment by vsalvino** [comment]
Awesome, thanks!
